name: develop

on:
  pull_request:
  push:

jobs:

  linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dep
        run: |
          rustup component add clippy
          rustup component add rustfmt
      # https://github.com/EmbarkStudios/cargo-deny-action
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --all-features
          command: check advisories licenses sources bans
      - name: Run ci-generated
        run: make ci-generated
      - name: Run ci
        run: make ci
      - name: Run ci-asm
        run: make ci-asm
      - name: Run ci-asm-chaos
        run: make ci-asm-chaos
      - name: Run spawn tests in release
        run: cargo test test_spawn --release --features=asm -- --nocapture

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ci-asm
        run: make ci-asm

  windows:
    # We must use windows-2019 here, otherwise we will encounter some bugs, for futher details, see
    # https://github.com/yasm/yasm/issues/153
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Dep
        shell: pwsh
        # https://github.com/ScoopInstaller/Install#for-admin
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop install llvm
          scoop install yasm
      - name: Run ci-asm
        shell: pwsh
        run: |
          $env:path="C:\Users\runneradmin\scoop\apps\llvm\current;"+$env:path
          $env:path="C:\Users\runneradmin\scoop\apps\yasm\current;"+$env:path
          make ci-asm
