name: develop

on:
  pull_request:
  push:

jobs:

  linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dep
        run: |
          rustup component add clippy
          rustup component add rustfmt
      # https://github.com/EmbarkStudios/cargo-deny-action
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --all-features
          command: check advisories licenses sources bans
      - name: Run ci-generated
        run: make ci-generated
      - name: Run ci
        run: make ci
      - name: Run ci-asm
        run: make ci-asm
      - name: Run ci-asm-chaos
        run: make ci-asm-chaos
      - name: Run test suites
        run: |
          sudo apt install -y git \
                              build-essential \
                              autoconf \
                              automake \
                              autotools-dev \
                              libmpc-dev \
                              libmpfr-dev \
                              libgmp-dev \
                              gawk \
                              libtool \
                              patchutils \
                              libexpat-dev \
                              zlib1g-dev
          git clone https://github.com/nervosnetwork/ckb-vm-test-suite
          ln -snf .. ckb-vm-test-suite/ckb-vm
          docker run --rm -v `pwd`:/code nervos/ckb-riscv-gnu-toolchain:bionic-20210804 cp -r /riscv /code/riscv
          cd ckb-vm-test-suite
          git checkout 86480364649c9cb6ac01674fe51156e7cf50a31a
          git submodule update --init --recursive
          RISCV=`pwd`/../riscv ./test.sh
      - name: Run spawn tests in release
        run: cargo test test_spawn --release --features=asm -- --nocapture

  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ci-asm
        run: |
          sudo apt-get update -y
          sudo apt install -y git \
                              build-essential \
                              autoconf \
                              automake \
                              autotools-dev \
                              libmpc-dev \
                              libmpfr-dev \
                              libgmp-dev \
                              gawk \
                              libtool \
                              patchutils \
                              libexpat-dev \
                              zlib1g-dev \
                              gcc-aarch64-linux-gnu \
                              g++-aarch64-linux-gnu \
                              qemu-user-static
          rustup target add aarch64-unknown-linux-gnu
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-C link-args=-L -C link-args=/usr/lib/gcc-cross/aarch64-linux-gnu/11"
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER="qemu-aarch64-static -L /usr/aarch64-linux-gnu"
          cargo test --features=asm --target aarch64-unknown-linux-gnu

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ci-asm
        run: make ci-asm

  windows:
    # We must use windows-2019 here, otherwise we will encounter some bugs, for futher details, see
    # https://github.com/yasm/yasm/issues/153
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Dep
        shell: pwsh
        # https://github.com/ScoopInstaller/Install#for-admin
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop install llvm
          scoop install yasm
      - name: Run ci-asm
        shell: pwsh
        run: |
          $env:path="C:\Users\runneradmin\scoop\apps\llvm\current;"+$env:path
          $env:path="C:\Users\runneradmin\scoop\apps\yasm\current;"+$env:path
          make ci-asm
